# Generated by Django 6.0.6 on 2026-07-07 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Institution_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutionprofile',
            old_name='college_name',
            new_name='institution_name',
        ),
    ]
