# Generated by Django 6.0.6 on 2026-07-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institution_app', '0002_rename_college_name_institutionprofile_institution_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionprofile',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
