# Generated by Django 6.0.6 on 2026-07-04 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=50)),
                ('job_type', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr_app.hrprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
