# Generated by Django 6.0.6 on 2026-07-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr_app', '0002_post_job_delete_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='company_name',
            field=models.CharField(default='Gtec', max_length=150),
            preserve_default=False,
        ),
    ]
