# Generated by Django 6.0.6 on 2026-07-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr_app', '0003_hrprofile_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrprofile',
            name='company',
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
