# Generated by Django 6.0.6 on 2026-07-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr_app', '0004_remove_hrprofile_company_hrprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
