# Generated by Django 6.0.6 on 2026-07-04 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_job_application_studentresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.studentprofile'),
        ),
    ]
