# Generated by Django 6.0.6 on 2026-07-04 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr_app', '0002_post_job_delete_jobpost'),
        ('student_app', '0003_alter_studentresume_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Applied', max_length=30)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr_app.post_job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'job')},
            },
        ),
    ]
