# Generated by Django 6.0.6 on 2026-07-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ai_recommendation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ai_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='analysis_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
