# Generated by Django 6.0.6 on 2026-07-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_jobapplication_ai_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
