# Generated by Django 6.0.6 on 2026-07-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_studentprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='registerno',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
